### PR TITLE
Clarify README.md and fix install.sh

### LINKED ISSUE #1: ./install.sh wildcard and path wrong
In the `install.sh` it should be `sha3-workload` or whatever the cloned folder name is. Additionally, the wildcard in the script does not get expanded so it leads to a `*.json` file and a `path/to/*.json` link.

### PR DESCRIPTION
**Pull request by abejgonzalez**
Fixes #1

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -2,5 +2,7 @@
 set -e
 
 pushd ../
-ln -sf sha3/marshal-configs/*.json .
```
Comment (a0u) [inline install.sh:5]: There is no need to change this glob.  This results in a literal `*.json` only when there are no matches and the `nullglob` option is set in Bash (the default).

If you want to make this more robust, I suggest checking for `[ "${PWD##*/}" = 'sha3' ]`.
